default:
  api:
    port: 3000

  session:
    host: localhost
    port: 6379
    secret: keyboard cat

  github:
    client_id:
    client_secret:
    callback_url: http://localhost:3000/auth/github/callback

production:
  api:
    port: 5000
