name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - id: Deploy application
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
          ssh-private-key: ${{ secrets.PROD_PRIVATE_DEPLOY_KEY }}
          dokku-host: 'hub.asyncapi.io'
          app-name: 'app'
