name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Push to dokku
        uses: obrassard/action-dokku-deploy@v1.0.0
        with:
          dokku_repo: 'ssh://dokku@hub.asyncapi.io:22/app'
          ssh_key: ${{ secrets.PROD_PRIVATE_DEPLOY_KEY }}

